#USERS

### create user
POST {{base-url}}/users
Content-Type: application/json

{
  "username": "username{{$random.integer(1, 9)}}",
  "email": "test{{$random.integer(1, 9)}}@gmail.com",
  "password": "password"
}
### get user
GET {{base-url}}/users/{{userId}}

### delete user
DELETE {{base-url}}/users/{{userId}}

#PLANS

### get plans
GET {{base-url}}/plans?userId={{userId}}

### get plan
GET {{base-url}}/plans/2?userId={{userId}}

### create plan
POST {{base-url}}/plans
Content-Type: application/json

{
  "userId": "{{userId}}",
  "name": "Created plan {{$random.integer(1, 99)}}"
}

### delete plan
DELETE {{base-url}}/plans/2
###


#EVENTS

### get events
GET {{base-url}}/plans/{{planId}}/events?userId={{userId}}

### get event
GET {{base-url}}/plans/{{planId}}/events/4?userId={{userId}}

### create event
POST {{base-url}}/plans/{{planId}}/events
Content-Type: application/json

{
  "userId": "{{userId}}",
  "planId": "{{planId}}",
  "name": "Event {{$random.integer(1, 9)}}",
  "dtStart": 1734993924602,
  "dtEnd": 1735166724608,
  "invitedPersonsCount": {{$random.integer(1, 99)}},
  "cost": {{$random.integer(1, 99)}}
}

### update event
PATCH {{base-url}}/plans/2/events/2
Content-Type: application/json

{
  "userId": "{{userId}}",
  "planId": "{{planId}}",
  "name": "Updated Event {{$random.integer(1, 999)}}",
  "dtStart": 1734993924602,
  "dtEnd": 1735166724608,
  "invitedPersonsCount": {{$random.integer(1, 99)}},
  "cost": {{$random.integer(1, 99)}},
  "imageUrl": "/Users/mikita/WebstormProjects/other/myelino-test-server/data/images/randomImage0.7348952827332607.jpg"
}
